# Generated by Django 3.2.6 on 2021-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
