# Generated by Django 3.2.6 on 2021-08-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_shop_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
